package:
  name: coffee_poisson_solver
  version: 1.1

source:
  fn: CoFFEE_1.1.tar.gz
  url: https://data.mendeley.com/datasets/s2x4d542dc/1/files/602063ca-d751-4c5f-8d34-075b564b634d/CoFFEE_1.1.tar.gz
  md5: 34d1c7498feb98e89afcf79d801b00ce
  patches:
    # List any patch files here
    - 0001-Add-alternative-setup.py-script.patch

build:
  # entry_points:
  # Put any entry points (scripts to be generated automatically) here. The
  # syntax is module:function.  For example
  #
  # - msgpack-python = msgpack-python:main
  #
  # Would create an entry point called msgpack-python that calls msgpack-python.main()

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python
    - setuptools
    - mpi4py
    - numpy
    - scipy
    - matplotlib
    - ipython
    - jupyter
    - pandas
    - sympy
    - nose
  run:
    - python
    - mpi4py
    - numpy
    - scipy
    - matplotlib
    - ipython
    - jupyter
    - pandas
    - sympy
    - nose

test:
  # Python imports
  imports:
    - PoissonSolver

  # commands:
  # You can put test commands to be run here.  Use this to test that the
  # entry points work.
  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.
  # requires:
  # Put any additional test requirements here.  For example
  # - nose

about:
  home: https://data.mendeley.com/datasets/s2x4d542dc/1
  license: BSD 3-Clause
# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
